name: Commisery
on:
  workflow_call:
  pull_request:
    types: [edited, opened, synchronize, reopened]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This workflow uses a third-party action.
# The existence of a `permissions` key denies all
# permissions except those explicitly specified.
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Run Commisery
        uses: tomtom-international/commisery-action@bc4dbb43a159cc94986c104655153711eaeb8eb0 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          validate-pull-request: false
          validate-pull-request-title-bump: false
